### ISSUE TITLE
Incorrect variable name on EKS wiki page

### ISSUE THREAD

**Issue by cwb** [PaloAltoNetworks/cn-series-deploy#12]
## Documentation link

https://github.com/PaloAltoNetworks/cn-series-deploy/wiki/Deploy-an-EKS-cluster

## Describe the problem

In the Usage section, item 2, this page says to create a terraform.tfvars file and set "ssh_key." The name of this variable is actually "ssh_key_name" in the Terraform plan.

## Suggested fix

Change "ssh_key" on this wiki page to "ssh_key_name."

**Comment by mrichardson03** [comment]
Thanks!
